apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-webhook-relay.fullname" . }}-config
  labels:
    {{- include "nats-webhook-relay.labels" . | nindent 4 }}
data:
  WEBHOOK_DESTINATION: {{ .Values.config.webhookDestination | quote }}
  NATS_ADDRESS: {{ .Values.config.natsAddress | quote }}
  NATS_SUBJECT_PREFIX: {{ .Values.config.natsSubjectPrefix | quote }}
  NATS_RELAYED_SUBJECT_PREFIX: {{ .Values.config.natsRelayedSubjectPrefix | quote }}
  RUST_LOG: {{ .Values.config.rustLog | quote }}
