{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-webhook-relay.fullname" . }}-secrets
  labels:
    {{- include "nats-webhook-relay.labels" . | nindent 4 }}
type: Opaque
stringData:
  NATS_USER: {{ .Values.secrets.natsUser | quote }}
  NATS_PASS: {{ .Values.secrets.natsPassword | quote }}
{{- end }}
